server:
  port:9191

spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      routes:
        - id: USER-SERVICE
          url: lb://USER-SERVICE #lb is load balanced
          predicates:
           -Path=/users/**
          filters:
            - name: CircuitBreaker
              args:
                name: USER-SERVICE
                fallbackuri: forward:/userServiceFallBack
        - id: DEPARTMENT-SERVICE
          url: lb://DEPARTMENT-SERVICE #lb is load balanced
          predicates:
           -Path=/departments/**
          filters:
            - name: CircuitBreaker
              args:
                name: DEPARTMENT-SERVICE
                fallbackuri: forward:/departmentServiceFallBack

hystrix:
  command:
    fallbackcmd:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 4000

#Actuator Configuration
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream

#eureka:
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#    service-url:
#      defaultZone:http://localhost:8761/eureka/
#    instance:
#      hostname: localhost