server:
  port:9001

spring:
  application:
    name: DEPARTMENT-SERVICE
  zipkin:
    base-url: http://127.0.0.1:9411/ #zipkin server url is 9411

#Commenting the below code because we have added that in git repository
#eureka:
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#    service-url:
#      defaultZone:http://localhost:8761/eureka/
#    instance:
#      hostname: localhost